[platformio]
default_envs = waveshare_s3_154
src_dir = src

[env:waveshare_s3_154]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_16mb.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_src_filter =
    +<core/*.cpp>
    +<ui/*.cpp>
    +<platform/waveshare_s3/*.cpp>
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -I include
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM=1
    -D NERIPAL_WAVESHARE_S3_154=1
